GET http://localhost:4000/api/shifts

###

GET http://localhost:4000/api/shift/60e7cc6df581ee6f2ce31bac

###

POST http://localhost:4000/api/shift
Content-Type: application/json

{
    "name": "Afternoon Shift",
    "startTime": 1626544800000,
    "endTime": 1626573600000
}

### 

PUT http://localhost:4000/api/shift/60e7c7da29bad16e10420f9f
Content-Type: application/json

{
    "startTime": 1626357600000
}

###

DELETE http://localhost:4000/api/shift/60e9084317555b787bfb2d6e

###

POST http://localhost:4000/api/register
Content-Type:  application/json

{
    "email": "bpeterson1663@gmail.com",
   "firstName": "Brady",
    "lastName": "Peterson",
    "role": "administrator",
    "businessName": "Acme Inc"
}

###

POST http://localhost:4000/api/login
Content-Type: application/json

{
    "email": "bpeterson1661@gmail.com",
}

###

GET http://localhost:4000/api/authorized

###

DELETE http://localhost:4000/api/logout

###

POST http://localhost:4000/api/user
Content-Type: application/json

{
    "email": "bpeterson1661@gmail.com",
    "firstName": "Brady",
    "lastName": "Peterson",
    "role": "employee"
}

###

GET http://localhost:4000/api/users

###

GET http://localhost:4000/api/user/60eb38ac2d0a6b1dab5c84ab

### 
DELETE http://localhost:4000/api/user/60eb38ac2d0a6b1dab5c84ab

###
PUT http://localhost:4000/api/user/60eb38ac2d0ddb1dab5c84ab
Content-Type: application/json

{
  "firstName": "Brady"
}
