GET http://localhost:4000/api/shifts

###

GET http://localhost:4000/api/shift/60e7cc6df581ee6f2ce31bac

###

POST http://localhost:4000/api/shift
Content-Type: application/json

{
    "name": "Afternoon Shift",
    "startTime": 1626544800000,
    "endTime": 1626573600000
}

### 

PUT http://localhost:4000/api/shift/60e7c7da29bad16e10420f9f
Content-Type: application/json

{
    "startTime": 1626357600000
}

###

DELETE http://localhost:4000/api/shift/60e7c7da29bad16e10420f9f