const EmployeeActionTypes = {
  FETCH_ALL_START: 'FETCH_START',
  FETCH_EMPLOYEE_CREATE_START: 'FETCH_EMPLOYEE_CREATE_START',
  FETCH_EMPLOYEE_CREATE_SUCCESS: 'FETCH_EMPLOYEE_CREATE_SUCCESS',
  FETCH_EMPLOYEE_CREATE_FAILURE: 'FETCH_EMPLOYEE_CREATE_FAILURE',
}

export default EmployeeActionTypes
