const EmployeeActionTypes = {
  FETCH_ALL_START: 'FETCH_START',
  FETCH_EMPLOYEE_START: 'FETCH_EMPLOYEE_START',
  FETCH_EMPLOYEE_CREATE_SUCCESS: 'FETCH_EMPLOYEE_CREATE_SUCCESS',
  FETCH_EMPLOYEE_SUCCESS: 'FETCH_EMPLOYEE_SUCCESS',
  FETCH_EMPLOYEE_FAILURE: 'FETCH_EMPLOYEE_FAILURE',
  FETCH_ALL_EMPLOYEES_SUCCESS: 'FETCH_ALL_EMPLOYEES_SUCCESS',
  FETCH_DELETE_EMPLOYEE_SUCCESS: 'FETCH_DELETE_EMPLOYEE_SUCCESS',
}

export default EmployeeActionTypes
