const ShiftActionTypes = {
  FETCH_ALL_SHIFT_START: 'FETCH_ALL_SHIFT_START',
  FETCH_SHIFT_START: 'FETCH_SHIFT_START',
  FETCH_SHIFT_CREATE_SUCCESS: 'FETCH_SHIFT_CREATE_SUCCESS',
  FETCH_SHIFT_FAILURE: 'FETCH_SHIFT_FAILURE',
  FETCH_ALL_SHIFT_SUCCESS: 'FETCH_ALL_SHIFT_SUCCESS',
}

export default ShiftActionTypes
